name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/flight-delay-predictor || git clone git@github.com:ipekkocal/flight-delay-predictor.git && cd flight-delay-predictor
            git pull origin main

            docker build -t flight-delay-api .
            docker stop $(docker ps -q) || true
            docker run -d -p 8000:8000 \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              --name flight-delay-api \
              flight-delay-api
